name: Docker Image CI (GCR)

on:
   pull_request:
      branches:
         - 'main'
   push:
      branches:
         - 'main'
   workflow_dispatch:

jobs:
   build:
      runs-on: ubuntu-latest
      env:
         GITHUB_USERNAME: ${{ github.actor }}
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v3

         - name: lowercase USERNAME
           run: |
              echo "GITHUB_USERNAME=${GITHUB_USERNAME,,}" >>${GITHUB_ENV}

         - name: Login to Github Container Registry (GCR)
           uses: docker/login-action@v2
           with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

         - name: Build and push - Frontend
           uses: docker/build-push-action@v4
           with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: ghcr.io/${{ env.GITHUB_USERNAME }}/ums-backend:latest
